Pi 2131
ministryofjustice/hmpps-manage-a-supervision-ui pull request #75
Opened 2024-05-17 08:19 UTC by izzyL-DJ

2024-05-17 09:08 UTC, pmcphee77 requested changes

2024-05-17 09:08 UTC, pmcphee77 commented on server/views/pages/personal-details.njk
> +            <a href="{{ sentencePlan }}">View sentence plan in UI</a>
`sentencePlan` doesnt resolve to anything here. We need to add a ts function like this in `server/utils/utils.ts`

```
export const sentencePlanLink = () => {
  return `${config.sentencePlan.link}`
}
```
then add the function to the global nunJucks in `server/utils/nunJucksSetup.ts`

`njkEnv.addGlobal('sentencePlanLink', sentencePlanLink())`

Then the function can be called from the nunjucks template

`<a href="{{ sentencePlanLink }}" target="_blank">View sentence plan in UI</a>`

Also i think this should open in a new window hence i have specified `target="_blank"` above in the href

2024-05-20 08:16 UTC, pmcphee77 requested changes

2024-05-20 08:16 UTC, pmcphee77 commented on server/views/pages/personal-details.njk
> +            <a href="{{ sentencePlanLink }}" target="_blank">View sentence plan in UI</a>
should be sentencePlanLink()

2024-05-20 10:56 UTC, pmcphee77 submitted a review, later dismissed

2024-05-20 11:57 UTC, marcus-bcl approved these changes
Looks good

2024-05-20 11:57 UTC, marcus-bcl commented on server/views/pages/personal-details.njk
> +            <a href="{{ sentencePlanLink() }}" target="_blank">View sentence plan in UI</a>
Should this say something other than "UI"?  Maybe something like "View in the sentence plan service"? I'm not sure....

2024-05-22 08:02 UTC, pmcphee77 approved these changes

2024-05-22 13:02 UTC, merged